# Generated by Django 2.2.7 on 2019-12-25 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20191223_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
    ]
