# Generated by Django 2.2.7 on 2019-12-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_remove_datemaster_is_active'),
        ('landing', '0003_subscriber_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='master',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.Master'),
        ),
    ]
