# Generated by Django 2.2.7 on 2019-12-24 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_master_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haircut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haircut_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
            ],
            options={
                'verbose_name': 'Стрижка',
                'verbose_name_plural': 'Стрижки',
            },
        ),
        migrations.RemoveField(
            model_name='master',
            name='price',
        ),
        migrations.AddField(
            model_name='master',
            name='haircut',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.Haircut'),
        ),
    ]
