# Generated by Django 2.2.7 on 2019-12-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_auto_20191224_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haircut',
            name='haircut_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='название стрижки'),
        ),
        migrations.AlterField(
            model_name='haircut',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='master',
            name='descriptions',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Мастер'),
        ),
    ]
