# Generated by Django 2.2.7 on 2019-12-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_auto_20191224_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='haircut',
            old_name='haircut_name',
            new_name='name',
        ),
    ]
