# Generated by Django 2.2.7 on 2019-12-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_auto_20191225_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='position',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Должность'),
        ),
    ]
