# Generated by Django 2.2.7 on 2019-12-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_master_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='short_descriptions',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='master',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Должность'),
        ),
    ]
