# Generated by Django 2.2.7 on 2019-12-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_auto_20191225_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_men',
            field=models.BooleanField(default=True, verbose_name='М/Ж'),
        ),
    ]
