# Generated by Django 2.2.7 on 2019-12-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_master_is_men'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterimage',
            name='is_men',
            field=models.BooleanField(default=True, verbose_name='М/Ж'),
        ),
    ]
