# Generated by Django 2.2.7 on 2019-12-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_masterimage_is_men'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Мастер')),
                ('is_men', models.BooleanField(default=True, verbose_name='М/Ж')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Тип мастера',
                'verbose_name_plural': 'Тип мастеров',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.MasterCategory'),
        ),
    ]
