# Generated by Django 2.2.7 on 2019-12-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_auto_20191225_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='is_men',
        ),
        migrations.RemoveField(
            model_name='mastercategory',
            name='is_men',
        ),
        migrations.RemoveField(
            model_name='masterimage',
            name='is_men',
        ),
    ]
