# Generated by Django 2.2.7 on 2019-12-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_auto_20191225_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='haircut',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
