# Generated by Django 2.2.7 on 2019-12-25 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_haircut_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='master',
            name='short_descriptions',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Стрижки'),
        ),
    ]
