# Generated by Django 2.2.7 on 2019-12-25 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_auto_20191225_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('name', models.CharField(blank=True, default=None, max_length=155, null=True, verbose_name='Мастер')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Время мастера',
                'verbose_name_plural': 'Время мастеров',
            },
        ),
    ]
