# Generated by Django 2.2.7 on 2019-12-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0014_datemaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datemaster',
            name='is_active',
        ),
    ]
