# Generated by Django 2.2.7 on 2019-12-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbershop',
            old_name='custumer_phone',
            new_name='custumer_master',
        ),
    ]
