# Generated by Django 2.2.7 on 2019-12-24 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_auto_20191224_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='custumer_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='masterinbarbershop',
            name='date_per_master',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='masterinbarbershop',
            name='price',
            field=models.DecimalField(decimal_places=9, default=0, max_digits=10),
        ),
    ]
