# Generated by Django 2.2.7 on 2019-12-24 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_auto_20191224_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='custumer_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
