# Generated by Django 2.2.7 on 2019-12-24 18:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_auto_20191224_2115'),
        ('barbershop', '0004_auto_20191224_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterinbarbershop',
            name='date_per_master',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='haircut',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.Haircut'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='masterinbarbershop',
            name='haircut',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.Haircut'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='custumer_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='custumer_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='custumer_master',
            field=models.CharField(blank=True, default=None, max_length=48, null=True, verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='custumer_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='masterinbarbershop',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
