# Generated by Django 2.2.7 on 2019-12-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0005_auto_20191224_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinbarbershop',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
