# Generated by Django 2.2.7 on 2019-12-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0008_auto_20191224_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='haircut',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='custumer_haircut',
            field=models.CharField(blank=True, default=None, max_length=48, null=True, verbose_name='Стрижка'),
        ),
    ]
