# Generated by Django 2.2.7 on 2019-12-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0009_auto_20191225_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterinbarbershop',
            name='is_men',
            field=models.BooleanField(default=True, verbose_name='М/Ж'),
        ),
    ]
